projects[drupal][version] = "7.31"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[date][subdir] = "contrib"
projects[date][version] = "2.8"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[escape_admin][subdir] = "contrib"
projects[escape_admin][version] = "1.1"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-alpha3"

projects[inline_entity_form][subdir] = "contrib"
projects[inline_entity_form][version] = "1.5"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.2"

projects[media][subdir] = "contrib"
projects[media][version] = "2.0-alpha3"

projects[navbar][subdir] = "contrib"
projects[navbar][version] = "1.4"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc1"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.7"

projects[seckit][subdir] = "contrib"
projects[seckit][version] = "1.9"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[username_enumeration_prevention][subdir] = "contrib"
projects[username_enumeration_prevention][version] = "1.0"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[xmlsitemap][subdir] = "contrib"
projects[xmlsitemap][version] = "2.0"

projects[devel][subdir] = "development"
projects[devel][version] = "1.5"

projects[coder][subdir] = "development"
projects[coder][version] = "2.2"

libraries[backbone][download][type] = "get"
libraries[backbone][download][url] = "https://github.com/jashkenas/backbone/archive/1.0.0.zip"
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

libraries[foundation][download][type] = "get"
libraries[foundation][download][url] = "http://foundation.zurb.com/cdn/releases/foundation-5.4.0.zip"
libraries[foundation][directory_name] = "foundation"
libraries[foundation][type] = "library"

libraries[modernizr][download][type] = "get"
libraries[modernizr][download][url] = "https://github.com/Modernizr/Modernizr/archive/v2.7.1.zip"
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

libraries[underscore][download][type] = "get"
libraries[underscore][download][url] = "https://github.com/jashkenas/underscore/archive/1.5.0.zip"
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"